prims:
  target_box:
    position:
    - -0.1
    - 0.5
    - 0.03703
    orientation:
    - 1.0
    - 0.0
    - 0.0
    - 0.0
    size:
    - 0.1
    - 0.1
    - 0.1
  my_custom_box:
    position:
    - 0.0
    - 0.5
    - 0.4
    orientation:
    - 0.7073882691671998
    - 0.0
    - 0.0
    - 0.706825181105366
    size:
    - 0.5
    - 0.3
    - 0.01
  my_custom_box_2:
    position:
    - 0.15
    - 0.5
    - 0.2
    orientation:
    - 0.7073882691671998
    - 0.0
    - 0.0
    - 0.706825181105366
    size:
    - 0.5
    - 0.01
    - 0.4
  my_custom_box_3:
    position:
    - 0.0
    - 0.25
    - 0.2
    orientation:
    - 0.7073882691671998
    - 0.0
    - 0.0
    - 0.706825181105366
    size:
    - 0.01
    - 0.3
    - 0.4
  wall_1:
    position:
    - 0.0
    - 1.0
    - 0.5
    orientation:
    - 1.0
    - 0.0
    - 0.0
    - 0.0
    size:
    - 3.0
    - 0.2
    - 1.0
  wall_2:
    position:
    - 0.0
    - -1.0
    - 0.5
    orientation:
    - 1.0
    - 0.0
    - 0.0
    - 0.0
    size:
    - 3.0
    - 0.2
    - 1.0
  wall_3:
    position:
    - -1.0
    - 0.0
    - 0.5
    orientation:
    - 1.0
    - 0.0
    - 0.0
    - 0.0
    size:
    - 0.2
    - 1.8
    - 1.0
