rrt_explorer_node:
  ros__parameters:
    world_frame: "panda_link0"
    planning_group: "panda_arm"
    camera_link_name: "realsense_camera_world"
    frontier_cluster_distance: 0.5
    viewpoint_generation_radius: 0.8
    min_cluster_size: 10

    rrt:
      max_iterations: 40
      extension_range: 0.3

    bounds:
      min_x: -1.0
      max_x: 1.0
      min_y: -1.0
      max_y: 1.0
      min_z: 0.15
      max_z: 1.0
